#!/bin/sh
# $Id: emissary 496 2009-03-14 02:26:46Z ccorliss $
# emissary      This shell script takes care of starting and stopping emissary.
#
# chkconfig: 2345 99 10
# description: emissary provides support for handling of network events.

CONFIG_FILE=/etc/emissary/config.ini
##  Do this to ensure that RVM is used (invoke a subshell) if it exists on the system.  No harm otherwise
EMISSARY_EXECUTABLE=$(/bin/sh -l -c "ruby -rrubygems -e 'puts Gem.bindir'")/emissary

[ -f "${CONFIG_FILE}" ] || exit 0

start() {
    # Start daemon.
    echo -n "Starting emissary: "
    ${EMISSARY_EXECUTABLE} -d --config-file ${CONFIG_FILE} start
    [ "$?" -eq 0 ] && echo "ok" || echo "failed"
}

stop() {
    # Stop daemon.
    echo -n "Shutting down emissary: "
    /usr/bin/pkill -f '(emop_node|emissary-master)'
    [ "$?" -eq 0 ] && echo "ok" || echo "failed"
}

# See how we were called.
case "$1" in
  start)
    start;
    ;;
  stop)
    stop;
    ;;
  restart)
    echo 'Restarting emissary: '
    stop;
    start;
    ;;
  status)
    ${EMISSARY_EXECUTABLE} --config-file ${CONFIG_FILE} status
    ;;
  *)
    echo "Usage: emissary {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

